import type {
  Bank,
  BankForm,
  FieldGuidance,
  FormType,
  FormVersion,
  LanguageCode,
  Purpose,
  PurposeApplicability,
} from '../../domain/types';
import type { FormFieldDefinition, FormPageSpec } from '../../features/viewer/types';

/**
 * Reference dataset for the in-browser development backend.
 *
 * This file is the canonical seed for the tables described in db/schema.sql.
 * Everything here is deterministic and hand-authored:
 *  - purpose -> field applicability is reviewed by hand (see
 *    SBI_AOF_APPLICABILITY below). It is never inferred or generated by a model.
 *  - geometry is measured against one specific artwork revision and pinned by
 *    `artworkHash`; published versions are immutable.
 */

export interface MockCatalog {
  banks: Bank[];
  formTypes: FormType[];
  bankForms: BankForm[];
  formVersions: FormVersion[];
  formPages: (FormPageSpec & { formVersionId: string })[];
  formFields: FormFieldDefinition[];
  purposes: Purpose[];
  applicability: PurposeApplicability[];
  fieldGuidance: FieldGuidance[];
}

/* ------------------------------------------------------------------ banks -- */

export const BANKS: Bank[] = [
  { id: 'sbi', name: 'State Bank of India', slug: 'sbi', emblem: '8fbcd', popular: true, isActive: true },
  { id: 'hdfc', name: 'HDFC Bank', slug: 'hdfc', emblem: '1c19e', popular: true, isActive: true },
  { id: 'icici', name: 'ICICI Bank', slug: 'icici', emblem: '6f05a', popular: true, isActive: true },
  { id: 'bob', name: 'Bank of Baroda', slug: 'bob', emblem: '17fbf', popular: true, isActive: true },
  { id: 'canara', name: 'Canara Bank', slug: 'canara', emblem: '44085', popular: true, isActive: true },
  // Additional catalogue banks have no emblem asset exported from Figma yet;
  // the UI falls back to a monogram tile until the asset task is completed.
  { id: 'axis', name: 'Axis Bank', slug: 'axis', emblem: null, popular: false, isActive: true },
  { id: 'kotak', name: 'Kotak Mahindra Bank', slug: 'kotak', emblem: null, popular: false, isActive: true },
  { id: 'pnb', name: 'Punjab National Bank', slug: 'pnb', emblem: null, popular: false, isActive: true },
  { id: 'union', name: 'Union Bank of India', slug: 'union', emblem: null, popular: false, isActive: true },
];

/* ------------------------------------------------------------- form types -- */

export const FORM_TYPES: FormType[] = [
  {
    id: 'account-opening',
    titleKey: 'form.accountOpening.title',
    descriptionKey: 'form.accountOpening.description',
    icon: '3b03e',
  },
  {
    id: 'account-closure',
    titleKey: 'form.accountClosure.title',
    descriptionKey: 'form.accountClosure.description',
    icon: '66683',
  },
  {
    id: 'kyc-update',
    titleKey: 'form.kycUpdate.title',
    descriptionKey: 'form.kycUpdate.description',
    icon: '9fe10',
  },
  {
    id: 'address-change',
    titleKey: 'form.addressChange.title',
    descriptionKey: 'form.addressChange.description',
    icon: '3d89d',
  },
  {
    id: 'minor-to-major',
    titleKey: 'form.minorToMajor.title',
    descriptionKey: 'form.minorToMajor.description',
    icon: 'e300b',
  },
  {
    id: 'nomination',
    titleKey: 'form.nomination.title',
    descriptionKey: 'form.nomination.description',
    icon: '83a20',
  },
];

/** Purpose catalogue. Icons reuse existing exported Figma assets. */
export const PURPOSE_CATALOGUE: Record<string, { labelKey: string; shortLabelKey: string; icon: Purpose['icon'] }> = {
  'open-new': { labelKey: 'purpose.openNew', shortLabelKey: 'purpose.openNew.short', icon: '99eac' },
  'minor-to-major': { labelKey: 'purpose.minorToMajor', shortLabelKey: 'purpose.minorToMajor.short', icon: '6c1c7' },
  'update-details': { labelKey: 'purpose.updateDetails', shortLabelKey: 'purpose.updateDetails.short', icon: '9a0af' },
  'change-type': { labelKey: 'purpose.changeType', shortLabelKey: 'purpose.changeType.short', icon: '1d6c8' },
  other: { labelKey: 'purpose.other', shortLabelKey: 'purpose.other.short', icon: '0e2c4' },
  'close-account': { labelKey: 'purpose.closeAccount', shortLabelKey: 'purpose.closeAccount.short', icon: '66683' },
  'address-change': { labelKey: 'purpose.addressChange', shortLabelKey: 'purpose.addressChange.short', icon: '3d89d' },
  'kyc-update': { labelKey: 'purpose.kycUpdate', shortLabelKey: 'purpose.kycUpdate.short', icon: '9fe10' },
  'add-nominee': { labelKey: 'purpose.addNominee', shortLabelKey: 'purpose.addNominee.short', icon: '83a20' },
  'update-nominee': { labelKey: 'purpose.updateNominee', shortLabelKey: 'purpose.updateNominee.short', icon: '83a20' },
};

/** bankId -> formTypeIds offered by that bank. */
export const BANK_FORM_MATRIX: Record<string, string[]> = {
  sbi: ['account-opening', 'account-closure', 'kyc-update', 'address-change', 'minor-to-major', 'nomination'],
  hdfc: ['account-opening', 'kyc-update', 'address-change', 'nomination'],
  icici: ['address-change', 'kyc-update', 'account-closure'],
  bob: ['account-opening', 'nomination'],
  canara: ['account-closure', 'kyc-update'],
  axis: ['account-opening', 'kyc-update'],
  kotak: ['account-opening', 'nomination'],
  pnb: ['kyc-update', 'address-change'],
  union: ['account-opening'],
};

/** formTypeId -> purpose codes offered for that form. */
export const FORM_PURPOSE_MATRIX: Record<string, string[]> = {
  'account-opening': ['open-new', 'minor-to-major', 'update-details', 'change-type', 'other'],
  'account-closure': ['close-account', 'update-details', 'other'],
  'kyc-update': ['kyc-update', 'address-change', 'update-details'],
  'address-change': ['address-change', 'update-details'],
  'minor-to-major': ['minor-to-major', 'update-details'],
  nomination: ['add-nominee', 'update-nominee'],
};

/* ------------------------------------------------------- the SBI AOF form -- */

/** The only form whose artwork/geometry has been measured so far. */
export const SBI_ACCOUNT_OPENING_BANK_FORM_ID = 'sbi::account-opening';
export const SBI_AOF_VERSION_ID = 'sbi-aof-v1';
export const SBI_AOF_VERSION_LABEL = 'SBI-AOF-VER4-DEC2023';
export const SBI_AOF_ARTWORK_HASH = 'sha256:sbi-aof-ver4-dec2023:page1+page2peek';

export const SBI_AOF_PAGES: FormPageSpec[] = [
  {
    page: 1,
    width: 366,
    height: 537.25,
    artwork: 'sbi-aof-page-1',
    sheetClass: 'rounded-[2px] bg-white shadow-sheet',
  },
  {
    page: 2,
    width: 366,
    height: 186,
    artwork: 'sbi-aof-page-2-peek',
    sheetClass: 'rounded-[2px] bg-white opacity-85 shadow-peek',
    peek: true,
  },
];

interface FieldSeed {
  fieldKey: string;
  x: number;
  y: number;
  width: number;
  height: number;
  required: boolean;
  labelKey: string;
}

const SBI_AOF_FIELDS: FieldSeed[] = [
  { fieldKey: 'account-type', x: 16, y: 110.88, width: 221.333, height: 38.99, required: true, labelKey: 'field.accountType.label' },
  { fieldKey: 'photo', x: 241.333, y: 110.88, width: 108.667, height: 106, required: true, labelKey: 'field.photo.label' },
  { fieldKey: 'full-name', x: 16, y: 220.88, width: 334, height: 64.99, required: true, labelKey: 'field.fullName.label' },
  { fieldKey: 'date-of-birth', x: 16, y: 289.5, width: 136.833, height: 45.5, required: true, labelKey: 'field.dob.label' },
  { fieldKey: 'mobile', x: 156.833, y: 289.5, width: 193.167, height: 46.5, required: true, labelKey: 'field.mobile.label' },
  { fieldKey: 'address', x: 16, y: 391.75, width: 334, height: 63.135, required: true, labelKey: 'field.address.label' },
  { fieldKey: 'staff-senior', x: 16, y: 153.86, width: 221.333, height: 43.375, required: false, labelKey: 'field.staffSenior.label' },
  { fieldKey: 'minor-guardian', x: 16, y: 339.63, width: 334, height: 48.74, required: true, labelKey: 'field.minorGuardian.label' },
  { fieldKey: 'branch-use', x: 16, y: 457.88, width: 334, height: 46, required: false, labelKey: 'field.branchUse.label' },
];

/**
 * purpose code -> applicable field keys, for the SBI Account Opening Form.
 * Hand-reviewed. Every other field of the version is not applicable for that
 * purpose and must be left blank on the physical form.
 */
export const SBI_AOF_APPLICABILITY: Record<string, string[]> = {
  'open-new': ['account-type', 'photo', 'full-name', 'date-of-birth', 'mobile', 'address'],
  'minor-to-major': ['full-name', 'date-of-birth', 'mobile', 'address', 'minor-guardian'],
  'update-details': ['full-name', 'mobile', 'address'],
  'change-type': ['account-type', 'full-name', 'mobile'],
  other: ['full-name', 'mobile'],
};

export function sbiFieldId(fieldKey: string): string {
  return `${SBI_AOF_VERSION_ID}::${fieldKey}`;
}

/* ---------------------------------------------------------------- guidance -- */

type GuidanceText = { title: string; body: string; docLabel?: string };
type GuidanceSeed = Record<string, GuidanceText>;

const GUIDANCE_EN: GuidanceSeed = {
  'account-type': {
    title: 'Account type',
    body: 'Tick Savings Bank for a personal account. Choose Current Deposit only for a business or company account.',
  },
  photo: {
    title: 'Photograph',
    body: 'Affix one recent 3.5 cm × 4.5 cm colour photograph and sign across it before submitting the form.',
    docLabel: 'Doc 1: Photo',
  },
  'full-name': {
    title: 'Applicant full name',
    body: 'Write your name in block capitals exactly as it appears on your PAN or Aadhaar.',
    docLabel: 'Doc 2: PAN / Aadhaar',
  },
  'date-of-birth': {
    title: 'Date of birth',
    body: 'Fill DD / MM / YYYY exactly as printed on your Aadhaar or birth certificate.',
    docLabel: 'Doc 3: Aadhaar / birth certificate',
  },
  mobile: {
    title: 'Mobile number',
    body: 'Enter the mobile number registered with UIDAI. The bank sends the account-opening OTP to this number.',
  },
  address: {
    title: 'Current residential address',
    body: 'Copy your current residential address from a valid proof of address and include the PIN code.',
    docLabel: 'Doc 4: Proof of address',
  },
  'staff-senior': {
    title: 'Staff / senior citizen certificate',
    body: 'Fill this only if you are a bank staff member or claiming senior citizen benefits. Otherwise leave it blank.',
  },
  'minor-guardian': {
    title: 'Details for a minor account',
    body: 'Fill the guardian CIF number and the relationship with the minor. Leave blank for an adult account.',
  },
  'branch-use': {
    title: 'For branch office use',
    body: 'This section is completed by the bank. Do not write anything in it.',
  },
};

const GUIDANCE_TA: GuidanceSeed = {
  'account-type': {
    title: 'கணக்கு வகை',
    body: 'தனிநபர் கணக்குக்கு சேமிப்பு வங்கி என்பதைத் தேர்ந்தெடுக்கவும். வணிகக் கணக்குக்கு மட்டும் நடப்புக் கணக்கு.',
  },
  photo: {
    title: 'புகைப்படம்',
    body: 'சமீபத்திய 3.5 × 4.5 செ.மீ வண்ணப் புகைப்படத்தை ஒட்டி, அதன் குறுக்கே கையெழுத்திடவும்.',
    docLabel: 'ஆவணம் 1: புகைப்படம்',
  },
  'full-name': {
    title: 'விண்ணப்பதாரரின் முழுப் பெயர்',
    body: 'பான் அல்லது ஆதார் அட்டையில் உள்ளபடி உங்கள் பெயரை முழு எழுத்துகளில் எழுதவும்.',
    docLabel: 'ஆவணம் 2: பான் / ஆதார்',
  },
  'date-of-birth': {
    title: 'பிறந்த தேதி',
    body: 'ஆதார் அல்லது பிறப்புச் சான்றிதழில் உள்ளபடி நாள் / மாதம் / ஆண்டு என நிரப்பவும்.',
    docLabel: 'ஆவணம் 3: ஆதார் / பிறப்புச் சான்றிதழ்',
  },
  mobile: {
    title: 'கைபேசி எண்',
    body: 'ஆதாருடன் இணைக்கப்பட்ட கைபேசி எண்ணை எழுதவும். கணக்கு தொடங்கும் OTP இந்த எண்ணுக்கு வரும்.',
  },
  address: {
    title: 'தற்போதைய வீட்டு முகவரி',
    body: 'செல்லுபடியாகும் முகவரிச் சான்றில் உள்ளபடி அஞ்சல் குறியீட்டு எண் உட்பட முகவரியை எழுதவும்.',
    docLabel: 'ஆவணம் 4: முகவரிச் சான்று',
  },
  'staff-senior': {
    title: 'பணியாளர் / மூத்த குடிமகன் சான்று',
    body: 'வங்கிப் பணியாளராகவோ மூத்த குடிமகன் சலுகை பெறுபவராகவோ இருந்தால் மட்டும் நிரப்பவும். இல்லையெனில் காலியாக விடவும்.',
  },
  'minor-guardian': {
    title: 'மைனர் கணக்கு விவரங்கள்',
    body: 'மைனர் கணக்கிற்கு பாதுகாவலர் CIF எண் மற்றும் உறவு முறையை நிரப்பவும். வயது வந்த கணக்கிற்கு காலியாக விடவும்.',
  },
  'branch-use': {
    title: 'கிளை அலுவலக பயன்பாட்டுக்கு',
    body: 'இந்தப் பகுதியை வங்கி மட்டுமே நிரப்பும். இதில் எதையும் எழுத வேண்டாம்.',
  },
};

const GUIDANCE_HI: GuidanceSeed = {
  'account-type': {
    title: 'खाता प्रकार',
    body: 'व्यक्तिगत खाते के लिए बचत बैंक चुनें। चालू जमा केवल व्यावसायिक खाते के लिए है।',
  },
  photo: {
    title: 'फोटो',
    body: 'हाल का 3.5 × 4.5 सेमी रंगीन फोटो चिपकाएँ और उसके आर-पार हस्ताक्षर करें।',
    docLabel: 'दस्तावेज़ 1: फोटो',
  },
  'full-name': {
    title: 'आवेदक का पूरा नाम',
    body: 'पैन या आधार पर जैसा है वैसा ही नाम बड़े अक्षरों में लिखें।',
    docLabel: 'दस्तावेज़ 2: पैन / आधार',
  },
  'date-of-birth': {
    title: 'जन्म तिथि',
    body: 'आधार या जन्म प्रमाण पत्र के अनुसार दिन / माह / वर्ष भरें।',
    docLabel: 'दस्तावेज़ 3: आधार / जन्म प्रमाण पत्र',
  },
  mobile: {
    title: 'मोबाइल नंबर',
    body: 'आधार से जुड़ा मोबाइल नंबर लिखें। खाता खोलने का ओटीपी इसी नंबर पर आएगा।',
  },
  address: {
    title: 'वर्तमान आवासीय पता',
    body: 'वैध पते के प्रमाण से अपना वर्तमान पता पिन कोड सहित लिखें।',
    docLabel: 'दस्तावेज़ 4: पते का प्रमाण',
  },
  'staff-senior': {
    title: 'स्टाफ / वरिष्ठ नागरिक प्रमाण',
    body: 'केवल बैंक कर्मचारी या वरिष्ठ नागरिक लाभ लेने वाले ही भरें, अन्यथा खाली छोड़ें।',
  },
  'minor-guardian': {
    title: 'नाबालिग खाते का विवरण',
    body: 'नाबालिग खाते के लिए अभिभावक सीआईएफ नंबर और संबंध भरें। वयस्क खाते में खाली छोड़ें।',
  },
  'branch-use': {
    title: 'शाखा कार्यालय उपयोग हेतु',
    body: 'यह भाग बैंक भरता है। इसमें कुछ न लिखें।',
  },
};

const GUIDANCE_TE: GuidanceSeed = {
  'account-type': {
    title: 'ఖాతా రకం',
    body: 'వ్యక్తిగత ఖాతా కోసం పొదుపు బ్యాంకును ఎంచుకోండి. వ్యాపార ఖాతా కోసం మాత్రమే చాలూవడి ఎంచుకోండి.',
  },
  photo: {
    title: 'ఫోటో',
    body: 'ఇటీవలి 3.5 × 4.5 సెం.మీ రంగు ఫోటోను అతికించి, దానిపై అడ్డంగా సంతకం చేయండి.',
    docLabel: 'పత్రం 1: ఫోటో',
  },
  'full-name': {
    title: 'దరఖాస్తుదారు పూర్తి పేరు',
    body: 'పాన్ లేదా ఆధార్‌లో ఉన్నట్లుగా మీ పేరును పెద్ద అక్షరాలలో రాయండి.',
    docLabel: 'పత్రం 2: పాన్ / ఆధార్',
  },
  'date-of-birth': {
    title: 'పుట్టిన తేదీ',
    body: 'ఆధార్ లేదా జనన ధ్రువపత్రంలో ఉన్నట్లుగా రోజు / నెల / సంవత్సరం నింపండి.',
    docLabel: 'పత్రం 3: ఆధార్ / జనన ధ్రువపత్రం',
  },
  mobile: {
    title: 'మొబైల్ నంబర్',
    body: 'ఆధార్‌తో అనుసంధానించిన మొబైల్ నంబర్ రాయండి. ఖాతా తెరిచే OTP ఈ నంబర్‌కు వస్తుంది.',
  },
  address: {
    title: 'ప్రస్తుత నివాస చిరునామా',
    body: 'చెల్లుబాటు అయ్యే చిరునామా ధ్రువపత్రం నుండి పిన్ కోడ్‌తో సహా రాయండి.',
    docLabel: 'పత్రం 4: చిరునామా ధ్రువపత్రం',
  },
  'staff-senior': {
    title: 'సిబ్బంది / వృద్ధ పౌర ధ్రువపత్రం',
    body: 'బ్యాంకు సిబ్బంది లేదా వృద్ధ పౌర ప్రయోజనం పొందుతున్నవారు మాత్రమే నింపండి, లేకుంటే ఖాళీగా వదిలేయండి.',
  },
  'minor-guardian': {
    title: 'మైనర్ ఖాతా వివరాలు',
    body: 'మైనర్ ఖాతా కోసం సంరక్షకుడి CIF నంబర్ మరియు సంబంధాన్ని నింపండి. పెద్దల ఖాతాకు ఖాళీగా వదిలేయండి.',
  },
  'branch-use': {
    title: 'శాఖ కార్యాలయ ఉపయోగానికి',
    body: 'ఈ భాగాన్ని బ్యాంకు నింపుతుంది. ఇందులో ఏమీ రాయవద్దు.',
  },
};

const GUIDANCE_KN: GuidanceSeed = {
  'account-type': {
    title: 'ಖಾತೆ ಪ್ರಕಾರ',
    body: 'ವೈಯಕ್ತಿಕ ಖಾತೆಗೆ ಉಳಿತಾಯ ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ. ವ್ಯಾಪಾರಿ ಖಾತೆಗೆ ಮಾತ್ರ ಚಾಲ್ತಿ ಠೇವಣಿ.',
  },
  photo: {
    title: 'ಫೋಟೋ',
    body: 'ಇತ್ತೀಚಿನ 3.5 × 4.5 ಸೆಂ.ಮೀ ಬಣ್ಣದ ಫೋಟೋ ಅಂಟಿಸಿ, ಅದರ ಮೇಲೆ ಅಡ್ಡಲಾಗಿ ಸಹಿ ಮಾಡಿ.',
    docLabel: 'ದಾಖಲೆ 1: ಫೋಟೋ',
  },
  'full-name': {
    title: 'ಅರ್ಜಿದಾರರ ಪೂರ್ಣ ಹೆಸರು',
    body: 'ಪಾನ್ ಅಥವಾ ಆಧಾರ್‌ನಲ್ಲಿರುವಂತೆ ನಿಮ್ಮ ಹೆಸರನ್ನು ದೊಡ್ಡ ಅಕ್ಷರಗಳಲ್ಲಿ ಬರೆಯಿರಿ.',
    docLabel: 'ದಾಖಲೆ 2: ಪಾನ್ / ಆಧಾರ್',
  },
  'date-of-birth': {
    title: 'ಹುಟ್ಟಿದ ದಿನಾಂಕ',
    body: 'ಆಧಾರ್ ಅಥವಾ ಜನನ ಪ್ರಮಾಣಪತ್ರದಲ್ಲಿರುವಂತೆ ದಿನ / ತಿಂಗಳು / ವರ್ಷ ಭರ್ತಿ ಮಾಡಿ.',
    docLabel: 'ದಾಖಲೆ 3: ಆಧಾರ್ / ಜನನ ಪ್ರಮಾಣಪತ್ರ',
  },
  mobile: {
    title: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    body: 'ಆಧಾರ್‌ಗೆ ಜೋಡಿಸಿದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬರೆಯಿರಿ. ಖಾತೆ ತೆರೆಯುವ OTP ಈ ಸಂಖ್ಯೆಗೆ ಬರುತ್ತದೆ.',
  },
  address: {
    title: 'ಪ್ರಸ್ತುತ ವಾಸದ ವಿಳಾಸ',
    body: 'ಮಾನ್ಯ ವಿಳಾಸ ದಾಖಲೆಯಿಂದ ಪಿನ್ ಕೋಡ್ ಸಹಿತ ನಿಮ್ಮ ಪ್ರಸ್ತುತ ವಿಳಾಸ ಬರೆಯಿರಿ.',
    docLabel: 'ದಾಖಲೆ 4: ವಿಳಾಸ ದಾಖಲೆ',
  },
  'staff-senior': {
    title: 'ಸಿಬ್ಬಂದಿ / ಹಿರಿಯ ನಾಗರಿಕ ಪ್ರಮಾಣ',
    body: 'ಬ್ಯಾಂಕ್ ಸಿಬ್ಬಂದಿ ಅಥವಾ ಹಿರಿಯ ನಾಗರಿಕ ಸೌಲಭ್ಯ ಪಡೆಯುವವರು ಮಾತ್ರ ಭರ್ತಿ ಮಾಡಿ, ಇಲ್ಲದಿದ್ದರೆ ಖಾಲಿ ಬಿಡಿ.',
  },
  'minor-guardian': {
    title: 'ಅಪ್ರಾಪ್ತ ಖಾತೆ ವಿವರಗಳು',
    body: 'ಅಪ್ರಾಪ್ತ ಖಾತೆಗೆ ಪೋಷಕರ CIF ಸಂಖ್ಯೆ ಮತ್ತು ಸಂಬಂಧ ಭರ್ತಿ ಮಾಡಿ. ಪ್ರಾಪ್ತ ಖಾತೆಗೆ ಖಾಲಿ ಬಿಡಿ.',
  },
  'branch-use': {
    title: 'ಶಾಖಾ ಕಚೇರಿ ಬಳಕೆಗೆ',
    body: 'ಈ ಭಾಗವನ್ನು ಬ್ಯಾಂಕ್ ಭರ್ತಿ ಮಾಡುತ್ತದೆ. ಇದರಲ್ಲಿ ಏನನ್ನೂ ಬರೆಯಬೇಡಿ.',
  },
};

const GUIDANCE_BY_LANGUAGE: Record<LanguageCode, GuidanceSeed> = {
  en: GUIDANCE_EN,
  ta: GUIDANCE_TA,
  hi: GUIDANCE_HI,
  te: GUIDANCE_TE,
  kn: GUIDANCE_KN,
};

/* ------------------------------------------------------------------- seed -- */

function buildBankForms(): BankForm[] {
  const rows: BankForm[] = [];
  for (const [bankId, formTypeIds] of Object.entries(BANK_FORM_MATRIX)) {
    for (const formTypeId of formTypeIds) {
      rows.push({ id: `${bankId}::${formTypeId}`, bankId, formTypeId, isActive: true });
    }
  }
  return rows;
}

function buildFormVersions(bankForms: BankForm[]): FormVersion[] {
  return bankForms.map((bankForm) => {
    const isSbiAof = bankForm.id === SBI_ACCOUNT_OPENING_BANK_FORM_ID;
    return {
      id: isSbiAof ? SBI_AOF_VERSION_ID : `${bankForm.id}::v1`,
      bankFormId: bankForm.id,
      // Only the measured SBI revision has a printable label so far; the other
      // rows exist so the catalogue, search and filters are complete, and are
      // surfaced to the user as "not available yet".
      versionLabel: isSbiAof ? SBI_AOF_VERSION_LABEL : 'REV-PENDING',
      artworkHash: isSbiAof ? SBI_AOF_ARTWORK_HASH : 'sha256:pending',
      status: 'published' as const,
      publishedAt: isSbiAof ? '2023-12-01T00:00:00.000Z' : '2024-01-01T00:00:00.000Z',
    };
  });
}

function buildFormFields(): FormFieldDefinition[] {
  return SBI_AOF_FIELDS.map((field, index) => ({
    id: sbiFieldId(field.fieldKey),
    formVersionId: SBI_AOF_VERSION_ID,
    page: 1,
    x: field.x,
    y: field.y,
    width: field.width,
    height: field.height,
    fieldKey: field.fieldKey,
    labelKey: field.labelKey,
    required: field.required,
    sort: index,
  }));
}

function buildPurposes(bankForms: BankForm[]): Purpose[] {
  const rows: Purpose[] = [];
  for (const bankForm of bankForms) {
    const purposeCodes = FORM_PURPOSE_MATRIX[bankForm.formTypeId] ?? [];
    purposeCodes.forEach((code, index) => {
      const catalogue = PURPOSE_CATALOGUE[code];
      if (!catalogue) return;
      rows.push({
        id: `${bankForm.id}::${code}`,
        bankFormId: bankForm.id,
        labelKey: catalogue.labelKey,
        shortLabelKey: catalogue.shortLabelKey,
        icon: catalogue.icon,
        sort: index,
      });
    });
  }
  return rows;
}

function buildApplicability(): PurposeApplicability[] {
  const rows: PurposeApplicability[] = [];
  const applicableFieldKeys = new Set(Object.values(SBI_AOF_APPLICABILITY).flat());
  for (const [purposeCode, applicableKeys] of Object.entries(SBI_AOF_APPLICABILITY)) {
    const purposeId = `${SBI_ACCOUNT_OPENING_BANK_FORM_ID}::${purposeCode}`;
    for (const fieldKey of applicableFieldKeys) {
      rows.push({
        formVersionId: SBI_AOF_VERSION_ID,
        purposeId,
        fieldId: sbiFieldId(fieldKey),
        applicable: applicableKeys.includes(fieldKey),
      });
    }
  }
  return rows;
}

function buildGuidance(): FieldGuidance[] {
  const rows: FieldGuidance[] = [];
  for (const [languageCode, seed] of Object.entries(GUIDANCE_BY_LANGUAGE) as [LanguageCode, GuidanceSeed][]) {
    for (const field of SBI_AOF_FIELDS) {
      const text = seed[field.fieldKey];
      if (!text) continue;
      rows.push({
        fieldId: sbiFieldId(field.fieldKey),
        languageCode,
        title: text.title,
        body: text.body,
        docLabel: text.docLabel,
      });
    }
  }
  return rows;
}

export function buildMockCatalog(): MockCatalog {
  const bankForms = buildBankForms();
  const formVersions = buildFormVersions(bankForms);
  return {
    banks: BANKS,
    formTypes: FORM_TYPES,
    bankForms,
    formVersions,
    formPages: SBI_AOF_PAGES.map((page) => ({ ...page, formVersionId: SBI_AOF_VERSION_ID })),
    formFields: buildFormFields(),
    purposes: buildPurposes(bankForms),
    applicability: buildApplicability(),
    fieldGuidance: buildGuidance(),
  };
}
